service: guard-shifts-crud
provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::052694071526:role/GuardShiftsCrudLambda

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    TeamsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Teams
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableClass: STANDARD
        BillingMode: PAY_PER_REQUEST
